import * as THREE from 'three';
import { FULLSCREEN_VERT, glsl } from '../rendering/glsl';
import type { SubjectSource } from './SubjectSource';

/**
 * Builds the demo subject on the GPU, once, in tiles (so that no single draw
 * call runs long enough to trip a GPU watchdog at 2160 × 3840).
 */
export function createProceduralSubject(
  renderer: THREE.WebGLRenderer,
  opts: { width: number; height: number; seed: number; steps: number },
): SubjectSource {
  const material = new THREE.RawShaderMaterial({
    glslVersion: THREE.GLSL3,
    vertexShader: FULLSCREEN_VERT,
    fragmentShader: glsl('passes/subject.frag'),
    uniforms: {
      uSeed: { value: opts.seed },
      uOutput: { value: 0 },
      uSteps: { value: opts.steps },
      uResolution: { value: new THREE.Vector2(opts.width, opts.height) },
    },
    depthTest: false,
    depthWrite: false,
  });
  const quad = fullscreenTriangle(material);
  const scene = new THREE.Scene();
  scene.add(quad);
  const camera = new THREE.Camera();

  const make = (mipmaps: boolean, type: THREE.TextureDataType = THREE.UnsignedByteType): THREE.WebGLRenderTarget => {
    const rt = new THREE.WebGLRenderTarget(opts.width, opts.height, {
      type,
      format: THREE.RGBAFormat,
      generateMipmaps: mipmaps,
      minFilter: mipmaps ? THREE.LinearMipmapLinearFilter : THREE.LinearFilter,
      magFilter: THREE.LinearFilter,
      depthBuffer: false,
    });
    rt.texture.colorSpace = THREE.NoColorSpace;
    return rt;
  };

  const observed = make(true);
  const inferred = make(true);
  const data = make(false, THREE.HalfFloatType);
  data.texture.minFilter = THREE.NearestFilter;
  data.texture.magFilter = THREE.NearestFilter;

  const targets = [observed, inferred, data];
  const tilesY = Math.max(1, Math.ceil(opts.height / 480));
  const prevAutoClear = renderer.autoClear;
  renderer.autoClear = false;
  targets.forEach((rt, output) => {
    material.uniforms.uOutput.value = output;
    renderer.setRenderTarget(rt);
    renderer.clear();
    for (let i = 0; i < tilesY; i++) {
      const y0 = Math.floor((i * opts.height) / tilesY);
      const y1 = Math.floor(((i + 1) * opts.height) / tilesY);
      rt.scissor.set(0, y0, opts.width, y1 - y0);
      rt.scissorTest = true;
      renderer.render(scene, camera);
    }
    rt.scissorTest = false;
  });
  renderer.setRenderTarget(null);
  renderer.autoClear = prevAutoClear;

  // Observed and inferred carry mipmaps (regenerated by three.js after each
  // render into them): they feed the confidence-driven blur.

  material.dispose();
  quad.geometry.dispose();

  return {
    kind: 'procedural',
    width: opts.width,
    height: opts.height,
    observed: observed.texture,
    inferred: inferred.texture,
    data: data.texture,
    targets: [observed, inferred, data],
  };
}

export function fullscreenTriangle(material: THREE.Material): THREE.Mesh {
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.BufferAttribute(new Float32Array([-1, -1, 0, 3, -1, 0, -1, 3, 0]), 3));
  const mesh = new THREE.Mesh(geometry, material);
  mesh.frustumCulled = false;
  return mesh;
}
